# config-repo
# 数据源(用户数据)
spring:
  datasource:
    druid:
      user:
        url: jdbc:mysql://192.168.210.34:3306/cloud3.0_user?useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
        username: dev_write
        password: Aisino@dev#34
        #default-readOnly: true  # 只读
        initialSize: 30
        maxActive: 50
        minIdle: 30
        maxWait: 30000
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        validationQuery: SELECT 'x'
        timeBetweenEvictionRunsMillis: 30000
        minEvictableIdleTimeMillis: 300000
        
# 数据源(基础数据)
      sys:
        url: jdbc:mysql://192.168.210.34:3306/cloudaccount?useSSL=false&zeroDateTimeBehavior=convertToNull&serverTimezone=UTC
        username: dev_write
        password: Aisino@dev#34
        #default-readOnly: false  # 读写
        initialSize: 30
        maxActive: 50
        minIdle: 30
        maxWait: 30000
        poolPreparedStatements: true
        maxPoolPreparedStatementPerConnectionSize: 20
        validationQuery: SELECT 'x'
        timeBetweenEvictionRunsMillis: 30000
        minEvictableIdleTimeMillis: 300000
   
# 分布式事物日志路径
  jta:
    log-dir: E:\logs\transaction-log
